disabled_rules: # rule identifiers to exclude from running
    - file_length
    - function_body_length
    - missing_docs
    - private_outlet
    - cyclomatic_complexity
    - trailing_whitespace
    - identifier_name
    - implicit_getter
    - unused_optional_binding

opt_in_rules:
   - line_length
   - force_unwrapping
   - empty_count
   - trailing_semicolon

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

line_length:
    warning: 140
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
   